version: '3'
services:
  dev-apache-server:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/usr/local/apache2/htdocs
    container_name: 1005-apache-container